language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run test
branches:
  only:
    - master
    - dongsir
before_deploy:
  - npm run build
  - rm -rf ./src ./script
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: dongsir
